### ISSUE TITLE
Display errors and warnings after failed submission

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands-client#255]
## Acceptance Criteria
- [ ] When receiving a response code of 400 and the below JSON response, error messages and warning messages should be displayed in their own boxes.
- [ ] Warning box should be yellow and include the title "These warnings will not prevent the form from being saved, but may indicate a problem with the form." with the subtitle "If you are sure that you want to submit the form with warnings, fix any errors, check the "Ignore warnings" box next to the submit button and submit the form again."
- [ ] Error box should be red and include the title "These errors will prevent the form from being saved." with the subtitle "If you are sure that you want to submit the form with warnings, fix any errors, check the "Ignore warnings" box next to the submit button and submit the form again."
- [ ] If the warnings list is empty, the warning box should not be visible. (Same for errors)
- [ ] The error/warning boxes should be part of the same base page as the red flag count and submission buttons so that they are displayed irregardless of the selected form category.
- [ ] The "ignore warnings" button should only be visible if there are warnings in the response.
- [ ] If the “ignore warnings” checkbox has been selected when a form is submitted, the “ignore_warnings” attribute in the JSON message should be set to “True”. Otherwise, the attribute should be set to “False” or omitted from the JSON message.

## Mockup
![group](https://user-images.githubusercontent.com/7903547/38308049-8c246498-3835-11e8-9a21-bb10dc46997d.png)

## Failed submission response JSON
````
{
      
        "errors": [
                "Irf number: Invalid form number: invalid Border Station code.",
                "Interceptees: At least one interceptee must be listed."
        ],
        "warnings": [
                "Red flags: No red flags are checked",
                "Has signature: Form should be signed, though not required"
        ]
}

**Comment by scrishel** [comment]
For the first acceptance criteria, I would assume that the response code should be a 400 for a failed submission
For the fifth acceptance criteria, you refer to the "red flag error count".  Should that just be "red flag count"
The wording of the last acceptance criteria seemed awkward to me.  How about using the following:
If the “ignore warnings” checkbox has been selected when a form is submitted, the “ignore_warnings” attribute in the JSON message should be set to “True”.  Otherwise, the attribute should be set to “False” or omitted from the JSON message.

**Comment by amunn33** [comment]
Thanks, I got myself tripped up with the wording on the last one.
