### ISSUE TITLE
Submit vs Save for Later

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands-client#277]
## Acceptance Requirements
- [ ] When the "Save for Later" button is selected, the form should be submitted with an "in_progress" status.
- [ ] When the "Submit" button is selected on a new or "in_progress" form, the form should be submitted with an "approved" status.

## Status in JSON
``````
{
    "station_id": 0,
    "country_id": 1,
    "status": "approved",
    "storage_id": "1",
    "responses": [. . .],
    "cards": [. . .],
}
``````

**Comment by scrishel** [comment]
@benaduggan  @amunn33 
The "in purgatory" is still in the long term plans, but not included in the first round.  There are a couple of validations to be performed even in the "save for later" although the majority of validations will not be performed.  The current plan is to determine the validations performed to be based on the target status.  Would it be better if an action value is used instead of the status - action='save for later', action='approve' and in the future action='save purgatory'.  We could have separate endpoints for these, but then should we have different endpoints when warnings should be ignored?

**Comment by amunn33** [comment]
Yeah, I think action is a better term for what we're really sending (the goal of the submission), so wouldn't the logic for deciding which API to go to be about as much logic as sending the action?

**Comment by amunn33** [comment]
@bsell93 Here's this issue.
