### ISSUE TITLE
ID Profile Management Page

### ISSUE THREAD

**Issue by jsouthwo** [Tiny-Hands/tinyhands-client#85]
The ID Profile Management page will allow users with access to break links between names in an Alias Group and Known Persons. This page will be similar in appearance to the "Edit Address 2" page and accessed via the same profile dropdown in the top-right corner of the page.  

The ID Profile Page will consist of a table with several columns, including:
- Known Person
- Aliases (list any and all Aliases connected to the Known Person)
- IRF/VIF # (next to each name, link to the IRF and/or VIF in which the name is found)
- Date of most recent IRF of VIF

Clicking on the IRF or VIF link will bring up the corresponding page in a new tab. Clicking on the Known Person or any Alias will bring up the "Alias Matching" popup window. 

See https://trello.com/c/b6T3Ba2J for a description of Known Person, Alias Group and Alias Matching page.

Clicking on an alias, which displays the Alias Matching page, and clicking on No ID Match will break the link between that alias and the Known Person, converting the alias into a new Known Person entry.

[ID_Matching_Mockup.pdf](https://github.com/Tiny-Hands/tinyhands-client/files/528449/ID_Matching_Mockup.pdf)

> @amunn33 @andrewfennig @jahudlow
> 
> I read through this feature and I think it needs to be defined more clearly before moving forward. I think it would be cool if we could start making mockups/wireframes too for stuff like this because I think it helps think through the whole functionality before the development starts.
> 
> I know the data model moved forward a little bit last semester with the new person object, but I don't think it changed enough to support what this feature is proposing. Here are some of the questions I had when reading through this feature:
> - What is an Alias Group? Is it just a group of known people, or is there more information that would be associated with it?
> - What data should be stored in the known person model?
> - What would the alias matching page actually look like? The data that it would be storing wouldn't display super well in a typical table because of the nested objects that they have associated with them
> - If these known persons can be in IRFs and VIFs shouldn't the data collected be the same in both of those forms?
> - If we don't collect the same data in the IRF and VIF then what fields should be required on the person model?

-- Ben Duggan

[Trello card.](https://trello.com/c/HTdkfMjk/39-id-profile-management-page)

**Comment by andrewfennig** [comment]
From "New records checking - Check names of victims and traffickers for duplicates" Trello Card:

When VIF is entered, there should be a back check to see if name of victim(s) or trafficker(s) are duplicates from previous VIFs. Preferred pop-up to allow user to determine whether name is definitely duplicate, possible duplicate, or definite unique. If not definite, send to alternate page of all possible duplicates that can be separately determined.

Definitions
Interceptee is a person listed on a paper form whose information is being entered into Dream Suite
Known Person refers to data about a person already stored in Dream Suite.
Alias Group refers to a group of Known Persons who have previously been confirmed as referring to the same Interceptee.
Drop Down - Name
When entering an Interceptee's name, Dream Suite triggers fuzzy matching on characters as they are entered. The browser displays the match results as a drop-down list. Matches are formatted as columns in a table with one row per match. Columns in the table display:

Name
IRF number
IRF date
Additionally, when the user hovers over any row in the table, the associated person's photo will display to the right of the table. This design is to allow a larger photo to be displayed in the drop-down than if the photo was scaled to fit into the table.

All of these data form active links. When clicked, the name and photo links navigate to the Alias Matching pop-up window, which allows the user to indicate an alias for the interceptee being entered. The IRF number and IRF date links open a new window/tab containing the content of the associated IRF.

Drop Down - Phone
A similar drop-down should appear when the user enters characters of an Interceptee's phone number. The difference between the Name drop-down (above) is that the name column should be replaced by a phone number column. Otherwise functionality is identical.

Alias Matching
The Alias Matching window is a pop-up that allows the user to match an Interceptee with a Known Person (selected from the drop-down list just described). The Known Person may be part of an Alias Group. If so, information from all members of the Alias Group are retrieved and displayed in the Alias Matching pop-up. If not, only the Known Person's information is displayed. The following information, formatted in a table, is displayed for each Known Person:

Photo
Name
Phone number
Sex
Age
Address 1
Address 2
IRF number
IRF date
The pop-up has two action buttons:

No ID Match indicates that the Interceptee is not a match to the Known Person (or the Alias Group containing the known person). The pop-up will disappear and return the user to the main form.

ID Match indicates that the Interceptee is a match for the Known Person (or Alias Group). In this case, the pop-up disappears, returning the user to the main form. If an Alias Group was displayed in the pop-up, the Interceptee is added to that Alias Group. If only a single Known Person was displayed, the system creates a new Alias Group containing the existing Known Person with the Interceptee being entered.

In the "ID Match" case, the system will not populate any additional fields for the Interceptee. It will only indicate that the Interceptee has been added to an Alias Group by displaying the link icon (below). Having indicated an ID match, the user will continue to enter other data for the Interceptee as normal.

Link Icon
When an Interceptee becomes part of an Alias Group, the display of that Interceptee's information should be decorated with a link icon. For example, the list of Interceptees on the IRF should have an additional column in which the link icon could be displayed for those Interceptees who are part of an Alias Group. If an Interceptee is not part of an Alias Group, the link icon will be absent.

When clicked, the link icon should open a pop-up window that is similar to the Alias Matching pop-up. It should display the same table of information about the Alias Group containing the Interceptee. In addition, the table should highlight visually the Interceptee whose link icon was clicked. The action buttons on the pop up should be as follows:

No ID Match will pop down the window and cause the Interceptee to be removed from the alias group. This will also remove the link icon from the display of the Interceptee.

Cancel will pop down the window and leave the Interceptee associated with the Alias Group. The link icon will continue to be displayed for that Interceptee.
